spring:
  datasource:
    url: jdbc:postgresql://211.188.59.175:5432/memo
    username: postgres
    password: Egis2395!@
    driver-class-name: org.postgresql.Driver


logging:
  level:
    root: INFO
    org.mybatis: DEBUG  # ✅ MyBatis SQL 실행 로그 활성화
    org.apache.ibatis: TRACE  # ✅ MyBatis가 XML을 찾는 과정 로그 활성화


mybatis:
  mapper-locations: classpath:/mapper/**/*.xml # MyBatis XML 매퍼 경로
  type-aliases-package: memo.vo
  configuration:
    map-underscore-to-camel-case: true  # DB의 스네이크 케이스를 카멜 케이스로 변환
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 쿼리 로그 설정